- id: '1568010065291'
  alias: Exterior On at Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      group: 1
    service: insteon.scene_on
  - data:
      group: 2
    service: insteon.scene_on
  - data:
      entity_id: 
        - light.switchlinc_dimmer_4d_97_d9
    service: light.turn_on
- id: '1568103741415'
  alias: Exterior Off at Night
  trigger:
  - at: '22:30'
    platform: time
  condition: []
  action:
  - data:
      group: 1
    service: insteon.scene_off
  - data:
      group: 2
    service: insteon.scene_off
- id: '1568103741416'
  alias: Front Porch Off at Sunrise
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id:
      - light.switchlinc_dimmer_4d_97_d9
    service: light.turn_off
