- id: 'balcony_on_sunset'
  alias: Balcony On at Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  # Use scene for simultaneous response
  - service: insteon.scene_on
    data:
      group: 1
  # Hit lights individually to sync light states in HA
  - service: light.turn_on
    data:
      entity_id: 
        - light.front_balcony_guest
        - light.front_balcony_den

- id: 'balcony_off_night'
  alias: Balcony Off at Night
  trigger:
  - at: '22:30'
    platform: time
  condition: []
  action:
  - service: insteon.scene_off
    data:
      group: 1
  - service: light.turn_off
    data:
      entity_id: 
        - light.front_balcony_guest
        - light.front_balcony_den

- id: 'back_yard_on_sunset'
  alias: Back Yard On at Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: insteon.scene_on
    data:
      group: 2
  - service: light.turn_on
    data:
      entity_id: 
        - light.back_yard_sconce
        - light.garage_service_sconce
  - service: switch.turn_on
    data:
      entity_id:
        - switch.back_yard_ground_lights

- id: 'back_yard_off_night'
  alias: Back Yard Off at Night
  trigger:
  - at: '22:30'
    platform: time
  condition: []
  action:
  - service: insteon.scene_off
    data:
      group: 2
  - service: light.turn_off
    data:
      entity_id: 
        - light.back_yard_sconce
        - light.garage_service_sconce
  - service: switch.turn_off
    data:
      entity_id:
        - switch.back_yard_ground_lights

- id: 'front_porch_on_sunset'
  alias: Front Porch On at Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id:
      - light.front_porch_sconce

- id: 'front_porch_off_sunrise'
  alias: Front Porch Off at Sunrise
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id:
      - light.front_porch_sconce
