# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: "hassio.mtv.home.barkerzone.com:8123"

homeassistant:
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Enable discovery
discovery:
# Text to speech
tts:
  - platform: google_translate

recorder:
  exclude:
    entities:
      #- sun.sun # Don't record sun data
      #- sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date
      - sensor.obihai_last_reboot

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

insteon:
  port: /dev/ttyUSB0

konnected: !include konnected.yaml

camera:
  - platform: uvc
    nvr: unms.mtv.home.barkerzone.com
    key: !secret unifi_camera_key
    password: !secret unifi_camera_password

somfy_mylink:
  host: 192.168.110.28
  system_id: !secret somfy_system_id
  
august:
  login_method: phone
  username: !secret august_username
  password: !secret august_password

sensor:
  - platform: obihai
    host: obi.mtv.home.barkerzone.com
    username: admin
    password: !secret obihai_password

light:
  - platform: group
    name: "Balcony Lights"
    entities:
      - light.switchlinc_dimmer_4d_9b_19
      - light.switchlinc_dimmer_4d_a8_8f

  - platform: group
    name: "Back Yard Lights"
    entities:
      - light.switchlinc_dimmer_4d_a2_0d
      - light.switchlinc_dimmer_4d_97_e9
